#!/bin/bash
# Auto-generated by test-tube (https://github.com/williamFalcon/test-tube)
#SBATCH --time=24:00:00
#SBATCH --job-name=SINGLEGPUTESTLAUNCHv0
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --signal=USR1@300
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=st7ma784@gmail.com
#SBATCH -p gpu-medium
export CONDADIR=/storage/hpc/46/manders3/conda4/open-ce
export NCCL_SOCKET_IFNAME=enp0s31f6
export SLURM_NNODES=$SLURM_JOB_NUM_NODES
export wandb=9cf7e97e2460c18a89429deed624ec1cbfb537bc
source /etc/profile
module add opence
conda activate $CONDADIR
srun python /data/WeatherLearn/PTL/launch.py --learning_rate 0.0002 --embed_dim 512 --batch_size 16 --grid_size 1000 --method flat --WindowsMinutes 60 --mlp_ratio 4 --dir . --HPC True --MINIOHost 10.48.163.59 --MINIOPort 9000 --MINIOAccesskey minioadmin --MINIOSecret minioadmin --bucket_name convmap --time_step 1 --data_dir $global_scratch/convmap_data --cache_first True --precision 16 --accelerator gpu --num_trials 0