

x-minio-common: &minio-common
  image: minio/minio
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  command: server --console-address ":9001" --address ":9000" http://minio{1...4}/data
  expose:
    - "9000"
    - "9001"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  networks:
    - mynetwork
  labels:
    - "com.centurylinklabs.watchtower.enable=true"


services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1:/data

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2:/data


  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3:/data

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4:/data

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - mynetwork

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30


volumes:
  data1:
    driver: local
    driver_opts:
      type: 'none'
      device: '/mnt/drive1'
      o: 'bind'
  data2:
    driver: local
    driver_opts:
      type: 'none'
      device: '/mnt/drive2'
      o: 'bind'
  data3:
    driver: local
    driver_opts:
      type: 'none'
      device: '/mnt/drive3'
      o: 'bind'
  data4:
    driver: local
    driver_opts:
      type: 'none'
      device: '/mnt/drive4'
      o: 'bind'


networks:
  mynetwork: